const fs = require('fs');
const glob = require('glob');
const fromCWD = require('from-cwd');
const logger = require('../logger');
const { camelCase } = require('camel-case');

const banner = `// DO NOT TOUCH!
// AUTOGENERATED!

`;

exports.generate = function (
	inputPattern = fromCWD('src/pages/**/route.ts'),
	output = fromCWD('src/Services/Routes/index-all-generated.ts')
) {
	logger.start('Generating routes list');
	const result = glob
		.sync(inputPattern)
		.map((file) => {
			const path = file.replace(/\\/g, '/').replace(fromCWD('src/').replace(/\\/g, '/'), '').replace(/\.ts$/, '');
			const name = camelCase(path.replace(/(^pages\/|route$)/g, ''));
			return { path, name: name || '_homepage' };
		})
		.sort((a, b) => a.name.localeCompare(b.name))
		.map(({ path, name }) => `export { route as ${name} } from '${path}';`)
		.join('\n');

	fs.writeFileSync(output, banner + result);
	logger.outputDone(output);
};
