// DO NOT TOUCH!
// AUTOGENERATED!

/* eslint-disable @typescript-eslint/no-unused-vars */
namespace NodeJS {
	/* eslint-disable @typescript-eslint/naming-convention */
	interface ProcessEnv {
		NEXT_TELEMETRY_DISABLED: string;

		NODE_ENV: string;

		NEXT_PUBLIC_APP_HTTPS: string;

		NEXT_PUBLIC_ENABLE_DEV_TOOLS: string;

		NEXT_PUBLIC_APP_URL: string;

		NEXT_PUBLIC_ENABLE_CLASS_NAMES_HASHING: string;

		NEXT_PUBLIC_ENABLE_DESIGN_TOKENS_HASHING: string;

		GRAPHQL_API: string;

		GRAPHQL_INTROSPECT_INPUT: string;

		GRAPHQL_INTROSPECT_OUTPUT: string;

		I18N_OUTPUT_TKEYS: string;

		NEXT_PUBLIC_I18N_PLACES: string;

		NEXT_PUBLIC_I18N_CURRENT_PLACE: string;

		NEXT_PUBLIC_I18N_LOCALES: string;

		NEXT_PUBLIC_I18N_DEFAULT_LOCALE: string;
	}
}
