// DO NOT TOUCH!
// AUTOGENERATED!

export { route as _homepage } from 'pages/route';
export { route as privacyPolicy } from 'pages/privacy-policy/route';
export { route as userAgreement } from 'pages/user-agreement/route';
